version: "3"

services:
  terrama2:
    build: "terrama2"
  
  postgis:
    image: mdillon/postgis
    volumes:
      - dbdata:/var/lib/postgres/data
    ports:
      - 9998:5432

  webapp:
    build: webapp
    depends_on:
      - "terrama2"
  
  webmonitor:
    image: docker_terrama2
    depends_on:
      - "terrama2"
  
  geoserver:
    build: "geoserver"
    volumes:
      - "data:/data"
  
  collector:
    image: docker_terrama2
    command: ["terrama2_service", "COLLECTOR", "6543"]
    environment:
      - DISPLAY=$DISPLAY
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
  
  analysis:
    image: docker_terrama2
    command: ["terrama2_service", "ANALYSIS", "6544"]
    environment:
      - DISPLAY=$DISPLAY
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"

  view:
    image: docker_terrama2
    command: ["terrama2_service", "VIEW", "6545"]
    environment:
      - DISPLAY=$DISPLAY
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"

  alert:
    image: docker_terrama2
    command: ["terrama2_service", "ALERT", "6546"]
    environment:
      - DISPLAY=$DISPLAY
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"

volumes:
  data:
  dbdata: