version: "3"

services:
  terrama2:
    build: "terrama2"
  # Base image for PostgreSQL/PostGIS
  postgis:
    image: mdillon/postgis
    volumes:
      - dbdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
  # TerraMA2 Web Application
  webapp:
    build: webapp
    depends_on:
      - "terrama2"
    ports:
      - "36000:36000"
    links:
      - "postgis"
    volumes:
      - "data:/data"
  # TerraMA2 Web Monitor
  webmonitor:
    build: webapp
    ports:
      - "36001:36001"
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
  # GeoServer - Universal (without Tomcat)
  geoserver:
    build: "geoserver"
    ports:
      - "8080:8080"
    volumes:
      - "data:/data"
  # TerraMA2 Collector Service using TerraMA2 Base
  collector:
    image: docker_terrama2
    entrypoint: 
      - terrama2_service
      - COLLECTOR
      - "6543"
    environment:
      - DISPLAY=$DISPLAY
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
  # TerraMA2 Analysis Service using TerraMA2 Base
  analysis:
    image: docker_terrama2
    entrypoint: 
      - terrama2_service
      - ANALYSIS
      - "6544"
    environment:
      - DISPLAY=$DISPLAY
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
  # TerraMA2 View Service using TerraMA2 Base
  view:
    image: docker_terrama2
    entrypoint: 
      - terrama2_service
      - VIEW
      - "6545"
    environment:
      - DISPLAY=$DISPLAY
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"
  # TerraMA2 Alert Service using TerraMA2 Base
  alert:
    image: docker_terrama2
    entrypoint: 
      - terrama2_service
      - ALERT
      - "6546"
    environment:
      - DISPLAY=$DISPLAY
    depends_on:
      - "terrama2"
    volumes:
      - "data:/data"
      - "/tmp/.X11-unix:/tmp/.X11-unix:ro"

volumes:
  # Shared Volume to mount along TerraMA2 images
  data:
  # PostgreSQL Volume
  dbdata: